# Generated by Django 6.0.6 on 2026-07-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_food_support_order_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
